### PR TITLE
Add test for detecting forbidden __constructor

### PR DESCRIPTION
**Pull request by enumag**
@spaze Okay here is another one. :sweat_smile: 

Not entirely sure if you want to do this. Note that the same could be done for other magic methods like __invoke, __clone and so on.

### CODE REVIEW

**Comment by spaze** [comment]
Hmm, another interesting one, thank you 🤣

Not sure either yet, first I thought you could disable classes with PHP's [`disable_classes` config option](https://www.php.net/manual/en/ini.core.php#ini.disable-classes) but
> This directive must be set in `php.ini` For example, you cannot set this in `httpd.conf`.
Which is a no-go for at least some projects so maybe disallowing constructors would make sense.

Here are some notes to self (or to anyone who'd like to do this sooner than me):

Constructor is not a method call as such and `MethodCalls::processNode()` will not be called on `new SomeClass`. To do that, a new class that `implements Rule` should be created with
```php
	public function getNodeType(): string
	{
		return Node\Expr\New_::class;
	}

	public function processNode(Node $node, Scope $scope): array
	{
		/** @var Node\Expr\New_ $node */
		$newNode = new Node\Expr\StaticCall($node->class, '__construct', $node->args, $node->getAttributes());
		return $this->disallowedHelper->getDisallowedMethodMessage($newNode->class, $newNode, $scope, $this->disallowedCalls);
	}
```

Converting `new SomeClass` to a `StaticCall` instance is a bit of a hack which I'm not sure I like but it works when the constructor is defined in the class (as is in the `ClassWithConstructor` class here).

It doesn't work when the constructor is not defined (`ClassWithoutConstructor` here) because reflection cannot find `__construct` and processing fails in both `hasMethod()` and `getMethod()` (when `hasMethod()` result is "overpowered"with `|| $node->name->name === '__construct'`):

https://github.com/spaze/phpstan-disallowed-calls/blob/b6d300dfe43e0d6895d2fe91d9b95e8db05e40cf/src/DisallowedHelper.php#L148-L149

So a different approach would probably be needed for constructors. As for other magic methods, I'd suspect it would be again totally different.

**Comment by enumag** [comment]
Nice analysis! Note that personally I don't really have a need for this. You just kinda provoked me into giving you another challenge so I delivered. 😁 Feel free to close it if you feel it doesn't belong to this package or not in this way. 😏

**Comment by spaze** [comment]
Yeah, you didn't disappoint. There are many cases that will not be detected, and I don't even aim for *detect-all-the-things* but maybe people would expect that constructors are detected so this should be handled somehow. Either by detecting them, or by documenting these are not detected, managing expectations.

Another option how to detect them is to introduce another config params, something like `constructorCalls` and handle those separately from `methodCalls`, might make the code a bit more readable.

I'll keep this PR open and will see what comes out of it.

**Comment by spaze** [comment]
Replaced by #30, the commit with the test was cherry-picked.

**Pull request closed without merging**
