### PR TITLE
Fix test class name

### PR DESCRIPTION
**Pull request by szepeviktor**
... so it matched the file name `tests/ControlStructures/ForeachControlStructureTest.php`

### CODE REVIEW

**Comment by szepeviktor** [comment]
A crude tool.
```
find -type f -name "[A-Z]*.php" | xargs -I% -- bash -c 'grep -q -m1 "^\(class\|abstract class\|final class\|interface\)\? $(basename -s .php %)" "%" || echo "Classname not found: %"'
```

**Comment by spaze** [comment]
Nice catch, thanks! I think phpcs may be able to find it as well, of configured, possibly using [this rule](https://github.com/slevomat/coding-standard/blob/master/doc/files.md#slevomatcodingstandardfilestypenamematchesfilename). I'll look into it.

**Comment by spaze** [comment]
Thanks! (Introduced in #257 by not fully removing the original class name from the copy/pasted file)

**Comment by szepeviktor** [comment]
Glad to contribute.

For PSR-4 there is `composer dump-autoload --dev --optimize --strict-psr`

**Comment by spaze** [comment]
> For PSR-4 there is `composer dump-autoload --dev --optimize --strict-psr`

Cool, though it doesn't seem to detect the case fixed here:

```
$ composer dump-autoload --dev --optimize --strict-psr
Generating optimized autoload files
Generated optimized autoload files containing 1920 classes
$ echo $?
0
$ grep extends ./tests/ControlStructures/ForeachControlStructureTest.php
class WhilForeachControlStructureTest extends RuleTestCase
```

**Comment by szepeviktor** [comment]
> it doesn't seem to detect the case fixed here:

Of course! Tests are not PSR-4 but "classmap".

**Comment by spaze** [comment]
Ah sorry, I see now what you mean. I thought the "For PSR-4 ..." comment was somehow related to this issue. Turns out, it wasn't, or at least not directly :-)

**Pull request merged**
