### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by xificurk**
PHP 8.0 is coming soon...

### CODE REVIEW

**Comment by xificurk** [comment]
The build fails because coding standard cannot be installed, which should be resolved in spaze/coding-standard#1

**Comment by xificurk** [comment]
@spaze Would you please take a look at this? Is there anything else I should look into?

**Comment by spaze** [comment]
Hey @xificurk, thanks for the PR! Got a little busy, I'll look into it now. I'd like to try without the *setup-php* action though.

**Comment by spaze** [comment]
I'll go with that *setup-php* action for now, and remove it once PHP 8 is supported directly by ubuntu-latest.

Thanks for the PR!

**Comment by xificurk** [comment]
Great, thank you for the new release.

**Pull request merged**
