### PR TITLE
[WIP] Introduce PHPCS

### PR DESCRIPTION
**Pull request by szepeviktor**
Only ~~two~~ 3 sniffs were excluded from PSR-2 :)

### CODE REVIEW

**Comment by spaze** [comment]
Thanks, closing curly brace should have one empty line, don't remove that.

**Comment by szepeviktor** [comment]
Done.

**Comment by spaze** [comment]
Is the whole `PSR2.Classes.ClassDeclaration` sniff needed to be excluded just for that one empty line? If not, can you please configure it that the config excludes only the needed sniff?

**Comment by szepeviktor** [comment]
> ERROR: The specified sniff code "PSR2.Classes.ClassDeclaration.CloseBraceAfterBody" is invalid

We need a config file...

**Comment by spaze** [comment]
I'd also like to use some more modern sniffs (like PSR-12 or Slevomat) before adding CS to CI.

**Comment by szepeviktor** [comment]
I leave it up to you.

Please continue from here...

**Comment by spaze** [comment]
Please squash those commits into one.

Too bad you don't want to finish the PR but thanks for what you've done anyway.

**Comment by szepeviktor** [comment]
I mean I'm not able to work before you decide what coding standard to follow :)

**Comment by szepeviktor** [comment]
I see.

You may remember that there are 3 basic tests: syntax, CS, static analysis.
Those are the building blocks of PHP projects.

**Comment by spaze** [comment]
That's not generally accepted view or convention but ok, whatever floats *your* boat.

**Comment by szepeviktor** [comment]
Yes, it is only a _must_ for my clients.

**Comment by spaze** [comment]
That's great but you sure know I'm not your client :-) You don't need to apply your client rules on a code you're not maintaining, that's not how it should work. And just for the record, those test categories are cool, I run some of them in CI, other in my IDE.

**Pull request closed without merging**
