### PR TITLE
Composer > Define allowed plugins

### PR DESCRIPTION
**Pull request by ruudk**
Needed for Composer 2.2.0 (found with 2.2.0-RC1)
```
composer self-update --preview
```

### CODE REVIEW

**Comment by ruudk** [comment]
@spaze Tried to fix the code style error but I believe it's coming from upstream `spaze/coding-standard`. It should not append `,` in function arguments as that is not available on PHP 7.1 and 7.2.

**Comment by spaze** [comment]
Yeah, right, the coding standard has started requiring trailing comma [recently](https://github.com/spaze/coding-standard/releases/tag/v0.0.12) I'll see if it can be enforced only for 7.3+.

At first I thought of dropping support for unsupported PHP versions but as PHPStan still supports them I think it would be worth the time to support those as well.

**Comment by ruudk** [comment]
I fixed it :)

**Comment by spaze** [comment]
Note to (mostly) self: the plugin is loaded because it's required by Slevomat Coding Standard which in turn is required by coding standard of yours truly: https://github.com/slevomat/coding-standard/blob/ec0e91393abbebca72de1e47e27ed98cf48f5fb1/composer.json#L16

**Review by spaze — APPROVED** [review]
LGTM, thanks! 🤘

**Pull request merged**
