### PR TITLE
Introduce PHPStan

### PR DESCRIPTION
**Pull request by szepeviktor**
From  #13

Done in separate commits.

### CODE REVIEW

**Comment by szepeviktor** [comment]
1 thing is waiting for you.

```
 ------ ---------------------------------------------------------------- 
  Line   DisallowedHelper.php                                            
 ------ ---------------------------------------------------------------- 
  79     Access to an undefined property PhpParser\Node\Expr::$name.     
  79     Access to an undefined property PhpParser\Node\Scalar::$value.  
 ------ ---------------------------------------------------------------- 
```

Please help me resolve this.

**Comment by szepeviktor** [comment]
Maybe https://github.com/phpstan/phpstan-src/commit/b48dfc0dabdae984023919090bff802dd606a7aa ?

**Comment by szepeviktor** [comment]
This is the 1 remaining commit having something new.
https://github.com/spaze/phpstan-disallowed-calls/pull/14/commits/3a0c1601263d7c2220501706cccd2667176feeb1

**Comment by spaze** [comment]
Hey, thanks for those commits. I've cherrypicked them to create new PRs (#15 #16 #17) and slightly modified them (more files to LF, and some other tiny changes). PHPStan is now running on level 1 but at least it's not throwing warnings, can work from there to reach higher levels.

**Pull request closed without merging**
