### PR TITLE
Enhance CI

### PR DESCRIPTION
**Pull request by szepeviktor**
When we have no lock file we should do an `update`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
No CI for PR-s?? 😿

**Comment by spaze** [comment]
Why `update` instead of `install`?

PR should also be CI'd, I'll do that as part of switching to GitHub Actions.

**Comment by szepeviktor** [comment]
> Why `update` instead of `install`?

Please read the top comment :)

**Comment by spaze** [comment]
Thanks, I have, please don't assume otherwise. I have also read [the documentation](https://getcomposer.org/doc/01-basic-usage.md#installing-dependencies) which says:

---

## Installing dependencies

To install the defined dependencies for your project, run the
[`install`](03-cli.md#install) command.

```sh
php composer.phar install
```

When you run this command, one of two things may happen:

### Installing without `composer.lock`

If you have never run the command before and there is also no `composer.lock` file present,
Composer simply resolves all dependencies listed in your `composer.json` file and downloads
the latest version of their files into the `vendor` directory in your project.

---

It also says:
> To update to the latest versions, use the `update` command. This will fetch the latest matching
versions (according to your `composer.json` file) and update the lock file
with the new versions. (This is equivalent to deleting the `composer.lock` file
and running `install` again.)

My question is genuine because I might be missing something.

I'll close this for now, feel free to reopen if you'd like to explain and back your changes with some references or science and stop wasting everyone's time. Thanks.

**Comment by szepeviktor** [comment]
I am sorry.

Composer 2 warns when there is no lock file

https://github.com/composer/composer/blob/6186c7f36f509c7476f4ffe947ad35704301b1ec/src/Composer/Installer.php#L212

**Comment by spaze** [comment]
Aha, thanks. Composer has started throwing a warning in version 2.0.0-alpha1 here: https://github.com/composer/composer/commit/e26405d8583dfc7e6083d3af2c5255cfc5cc2e81

Composer 2 is now at 2.0.0-alpha3, i'll change to `update` when moving to GitHub Actions in #8. Hopefully I'll do that before Composer 2 GA. Thanks.

**Pull request closed without merging**
